services:
  vllm:
    image: public.ecr.aws/q9t5s3a7/vllm-cpu-release-repo:latest
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN}
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - "8000:8000"
    ipc: host
    command: --model facebook/opt-125m --device cpu --dtype float32
    
  whisper:
    image: sefboonen/carevoice-whisper:latest
    ports:
      - "9000:9000"
    restart: unless-stopped
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - ORT_LOGGING_LEVEL=3
      - DEVICE_MODE=cpu
      - MODEL_NAME=tiny
      - COMPUTE_FLOAT=int8
