services:
  whisper:
    image: sefboonen/carevoice-whisper:cudo
    ports:
      - "9000:9000"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - ORT_LOGGING_LEVEL=3