services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    ports:
      - "3000:3000"
    environment:
      - WHISPER_SERVER_URL=${WHISPER_SERVER_URL}
      - LLM_SERVER=${LLM_SERVER}
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend