services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    ports:
      - "3000:3000"
    environment:
      - WHISPER_SERVER_URL=ws://77.104.167.148:40353  # Production Whisper server
      - LLM_SERVER=http://77.104.167.148:40465/v1/
    volumes:
      - ./backend:/app
      - ./frontend:/app/frontend