services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    ports:
      - "3000:3000"
    environment:
      - WHISPER_SERVER_URL=ws://host.docker.internal:9000
      - LLM_SERVER=ws://host.docker.internal:8000
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend